### ISSUE TITLE
Nodejs流学习系列之二: Writable Stream

### ISSUE THREAD

**Issue by linxiaowu66** [linxiaowu66/doumi-blog-comments#174]
https://blog.5udou.cn/#/blog/detail/NodejsLiu-Xue-Xi-Xi-Lie-Zhi-Er-Writable-Stream91 

 nodejs网关开发或多或少都会牵扯到流的使用，但每次的使用都是迷迷糊糊、懵懵懂懂，总是踩完坑后才知道怎么使用，所以有必要深入学习一下Nodejs的流。学习是为了实践，因此这篇文章将利用两个很常用的demo来学习理论并实践。本来只打算一篇文章就写完的,后来看官网文档,越看越觉得一篇文章解决不来,于是打算使用3篇文章来阐述清楚nodejs流的原理。

**Comment by fzhange** [comment]
该方法用来写指定的数据到可写流中,如果返回true表明内部可用的缓存仍然小于highWaterMark。如果为true的话那就是内部缓存空间不够,此时写入数据就应该暂停直到接收到drain事件。但是并不表示此时你再往可写流写数据会丢数据,Nodejs仍然会缓存所有写入的chunks直到使用完所有的缓存,这个时候将会无条件地终止掉缓存数据.甚至在中断之前,高内存的使用将会导致低效的垃圾回收性能以及高RSS(指的是没有释放内存回系统即使这块内存不再使用).



这段没有读懂


如果超过watermark 那我去写 是能写进去的  那我把资源写到哪里去了呢  如果一直写下去内存会爆掉吗  上面那段话实在是没读懂

**Comment by linxiaowu66** [comment]
> Nodejs仍然会缓存所有写入的chunks直到使用完所有的缓存,这个时候将会无条件地终止掉缓存数据.甚至在中断之前,高内存的使用将会导致低效的垃圾回收性能以及高RSS(指的是没有释放内存回系统即使这块内存不再使用).

Nodejs仍然会缓存所有写入的chunks直到使用完所有的缓存,这个时候将会无条件地终止掉缓存数据.甚至在中断之前,高内存的使用将会导致低效的垃圾回收性能以及高RSS(指的是没有释放内存回系统即使这块内存不再使用).

这句话不是可以解决你这个问题吗？
